### ISSUE TITLE
The name of the repository could properly be better

### ISSUE THREAD

**Issue by kim-groenborg-nielsen** [NovoNordisk-OpenSource/connector#54]
Have you considered that the name "connector" for the repo, isn't good choice?
In my opinion it should be a little more descriptive and unique, e.g. link https://github.com/NovoNordisk-OpenSource/bifrost-open-telemetry-dotnet-exporter

You should also remember that the structure in GitHub is flat, so uniqueness of repo names are needed 😉

BTW nice to the amount of activity on the repository 🙂

**Comment by akselthomsen** [comment]
Thanks for reaching out 😃 

We decided to use `connector` as the repo name as well, since it is considered best practice when developing R packages that the package and repo names are the same - and we definitely need a short and easy package name.

I understand why in this broad GitHub organization it could be nice to have naming like `r-package-connector`, but think we will keep our current standard.

Originally we also considered getting a separate organization with a scope of clinical data science (partially for this reason), but we were advised to keep the open source contributions together here.
